[build-system]
requires = ["setuptools", "wheel", "setuptools-git-versioning<2"]
build-backend = "setuptools.build_meta"

[project]
name = "pycityagent"
version = "1.0.0"
description = "LLM-based城市模拟器agent构建库"
requires-python = ">=3.8"
dependencies = [
    "dashscope >= 1.14.0",
    "geojson >= 3.1.0",
    "numpy >= 1.26.3",
    "openai >= 1.8.0",
    "Pillow >= 10.2.0",
    "pycitysim >= 1.8.0",
    "citystreetview >= 1.1.0",
    "PyYAML >= 6.0.1",
    "Requests >= 2.31.0",
    "transitions >= 0.9.0"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["pycityagent*"]
