[build-system]
requires = ["setuptools>=41", "wheel", "setuptools-git-versioning<2"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true

[project]
name = "pycityagent"
authors = [
    {name = "Yuwei Yan", email = "pinkgranite86@gmail.com"}
]
description = "LLM-based城市环境agent构建库"
keywords = ["agent", "city", "LLM"]
readme = "README.md"
license = {file = "LICENSE"}
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
    aiohttp==3.10.10
    citystreetview==1.2.4
    dashscope==1.14.1
    geojson==3.1.0
    grpcio==1.62.0
    grpcio==1.67.1
    matplotlib==3.7.1
    networkx==3.4.2
    numpy==1.24.1
    openai==1.54.3
    Pillow==11.0.0
    protobuf==5.28.3
    pycitydata==1.0.0
    pycityproto==2.0.0a8
    pycitysim==1.12.2
    Requests==2.32.3
    Shapely==2.0.6
    sidecar==0.7.0
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/tsinghua-fib-lab/pycityagent"
Repository = "https://github.com/tsinghua-fib-lab/pycityagent.git"
Issues = "https://github.com/tsinghua-fib-lab/pycityagent/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["pycityagent*"]
