llm_request:
  request_type: zhipuai
  api_key: <YOUR-API-KEY> # Please replace with the API key obtained from the LLM provider website.
  model: GLM-4-Flash # The name of the model to be used.

simulator_request:
  task_name: "citysim" # The name of the simulation task, affect the directory name for log output
  max_day: 1 # Defines the maximum number of days for the simulation.
  start_step: 0 # The initial step of the simulation in seconds.
  total_step: 86400 # Total steps in the simulation in seconds.
  log_dir: log # Directory where simulator logs will be stored.
  min_step_time: 1000 # Minimum execution time (in milliseconds) per step.

mqtt:
  server: <MQTT-BROKER> # Specify the MQTT server address here.
  port: 1883 # Port number on which the MQTT service is running.
  username: <USER-NAME> # Username for MQTT server authentication.
  password: <PASSWORD> # Password for MQTT server authentication.

map_request:
  file_path: data/beijing_map.pb # Path to the map file, reference to step1.

metric_request:
  mlflow: 
      username: <USER-NAME> # Username for MLflow authentication.
      password: <PASSWORD> # Password for MLflow authentication.
      mlflow_uri: <MLFLOW-URI> # URI pointing to the MLflow tracking server.

pgsql:
  enabled: true # Whether PostgreSQL database integration is enabled.
  dsn: <DSN> # Data source name for connecting to PostgreSQL.

avro:
  enabled: true # Whether Avro serialization is enabled.
  path: <AVRO-PATH> # Directory path for storing cached data or serialized files.
