llm_request:
  text_request:
    request_type: <YOUR_PROVIDER>
    api_key: <YOUR_API_KEY>
    model: <YOUR_MODEL>
  img_understand_request:
    request_type: none
    api_key: none
    model: none
  img_generate_request:
    request_type: none
    api_key: none
    model: none

simulator_request:
 simulator:
  min_step_time: 1
 mqtt:
  server: <MQTT-SERVER>
  username: <USER-NAME>
  port: <PORT> 
  password: <PASSWORD>
 map_request:
  mongo_uri: <MONGO_URI>
  mongo_db: srt
  mongo_coll: map_beijing_extend_20241201
  cache_dir: ./ignore
 streetview_request:
  engine: baidumap / googlemap
  mapAK: baidumap api-key (if you use baidumap engine)
  proxy: googlemap proxy (if you use googlemap engine)

metric_request:
  mlflow: 
    username: <USER-NAME>
    password: <PASSWORD>
    mlflow_uri: <MLFLOW-URI>

storage:
  pgsql:
   enabled: true
   dsn: <DATA-SOURCE-NAME>
